//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//using System;
using UnityEngine;
//using System.Collections;
//using System.IO;
using System.Collections.Generic;

public class CommonScene1
{
	public static List<Vector3> definePath()
	{
		List<Vector3> pathPts = new List<Vector3> ();
		GameObject sp = (GameObject)GameObject.Find ("StartPoint");
		GameObject ep = (GameObject)GameObject.Find ("EndPoint");
		pathPts.Add(sp.transform.position);
		//first_point = pathPts [0];
		pathPts.Add(ep.transform.position);
		findPath (pathPts);//straight Line points
		return pathPts;
	}
	private static void findPath (List<Vector3> pathPts)
	{
		int iterations = 6;//increase to increase number of points on path
		for (int i=0; i<iterations; i++)
		{
			int k=0;
			int numPoints = pathPts.Count;
			for(int j=0;j<numPoints-1;j++)
			{
				Vector3 newVect = (pathPts[k]+pathPts[k+1])/2;
				//Debug.Log(newVect);
				pathPts.Insert(k+1,newVect);
				k+=2;
			}
		}
	}
}


