//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.IO;
using System.Collections.Generic;
using UnityEditor;

	public class MyHashTableOptimal
	{
		public Vector3 ptKey;
		public List<Vector3> listValue;
		public MyHashTableOptimal ()
		{
			ptKey = Vector3.zero;
			listValue = new List<Vector3> ();
		}
	}


