//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//using System;
using UnityEngine;
using System.Collections.Generic;
public class NodeShadow
{
	public NodeShadow ()
	{
		children = new List<NodeShadow> ();
	}
	public NodeShadow (Vector3 pt)
	{
		currPt = pt;
		children = new List<NodeShadow> ();
	}
	Vector3 currPt;
	List<NodeShadow> children;
}


